package bind

import "strconv"

import "github.com/GoLangsam/sexpr"

const prefix byte = '_'

// Fresh returns a variable for the given name.
func (bind Ings) Fresh(name string) X {
	return sexpr.NewVariable(name)
}

/*
// V returns a fresh variable with an autogenerated reified name.
func (bind Ings) V() X {
	name := "~" + strconv.Itoa(bind.counter)
	bind.counter++
	return bind.Fresh(name)
}
*/

func isReifiedName(name string) bool {
	return name[0] == prefix
}

// Paginator provides a function to create a uniquely named
// fresh anonymous variable upon each evaluation.
// It is a helper for y.Reify.
func Paginator() func() X {
	var counter int
	return func() X {
		n := counter
		counter++
		return sexpr.NewVariable(string(prefix) + strconv.Itoa(n))
	}
}
